component_depth: 6
languages:
- typescript

- name: typescript
  production:
    exclude:
      - .*/install\.sh
      - /src/.*/constants\.ts
      - /src/.*/mutations\.ts
      - /src/.*/styles\.ts
      - /src/.*/queries\.ts
