component_depth: 6
languages:
- typescript

- name: typescript
  production:
    exclude:
      - .*/constants\.ts
      - .*/install\.sh
      - .*/mutations\.ts
      - .*/styles\.ts
      - .*/queries\.ts
